[package]
name = "run_here"
version = "0.1.0"
authors = ["maomao <5622876@qq.com>"]

[[bin]]
name = "run_here"
path = "src/main.rs"

[dependencies]
log = "0.4.6"
easy-logging = "*"

futures = "0.1"

actix={path = "../actix"}
